Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from os.path import join
import matplotlib.pyplot as plt

import os,sys,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
newpath = os.path.join(parent_dir, "script")
sys.path.insert(0, newpath) 
import fmpy_sim

directory = "../script/fmu"
fmu_filename = "PumpMotor.fmu"
path_fmu = join(directory, fmu_filename)


# Establish parameter bounds

n_simu = 5

dic_nominal = {
    "Pump.hn_coef[1]": -88.67,
    "Pump.hn_coef[2]": 43.15
}

dic_range = {
    "Pump.hn_coef[1]": np.linspace(-100, -60, n_simu),
    "Pump.hn_coef[2]": np.linspace(20, 60, n_simu)
}

# Define simulation parameters

list_input = ["Pump.hn_coef[1]"]
list_output = ["Pipe.Q"]
output_filter = list_input.extend(list_output)
final_time = 50

doe_data = np.array([[xx] for xx in dic_range[list_input[0]]])
kwargs = {
        "validate": False, "fmi_type": "ModelExchange", "solver": "CVode",
        "relative_tolerance": 1e-6, "stop_time": 50, "output": output_filter}

list_df = fmpy_sim.simulate_on_doe(
    list_input, doe_data, path_fmu, **kwargs)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mos[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpath[39;00m [38;5;28;01mimport[39;00m join
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m[38;5;241m,[39m[38;5;21;01msys[39;00m[38;5;241m,[39m[38;5;21;01minspect[39;00m
[1;32m      6[0m current_dir [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mdirname(os[38;5;241m.[39mpath[38;5;241m.[39mabspath(inspect[38;5;241m.[39mgetfile(inspect[38;5;241m.[39mcurrentframe())))

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

